version: "3"
services:
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed/
    restart: on-failure
    depends_on:
      - mongodb
  server:
    container_name: server
    build: ./server/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:27017/datapau
  client:
    container_name: client
    build: ./client/
    ports:
      - "9000:9000"
